### ISSUE TITLE
Cleanup stack defaults

### ISSUE THREAD

**Issue by arthurdm** [appsody/appsody-operator#88]
Now that Appsody stacks have default `app-deploy.yaml` (which can be generated by `appsody deploy --generate-only`), we should cleanup our default ConfigMap so that we don't have duplicate defaults.  

I propose that we take a similar approach to our `overrides` ConfigMap, where we leave the keys in there with empty values - even if that's not a complete list of all of the stacks, it demonstrates how a stack could be added.

We can keep our `generic` defaults, since we need those.

**Comment by navidsh** [comment]
I am debating if we should keep the default `service.port` at a minimum in the `ConfigMap`.
Otherwise, someone not using Appsody stack should specify correct `service.port` in order to have a working service. Although, you can argue they shouldn't use the same stack name in the `AppsodyApplication` CR.

**Comment by arthurdm** [comment]
I think it's fine to leave it out - we won't be able to keep up with the new stacks being introduced, so it's better to just keep consistent and not specify any of the defaults.

**Comment by navidsh** [comment]
Delivered. Closing.
